tomlname = "time-api"
main = "index.js"
compatibility_date = "2024-04-25"

[unsafe.bindings]
[[unsafe.bindings]]
name = "TIME_API_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"

[unsafe.bindings.TIME_API_RATE_LIMITER.simple]
limit = 100
period = 60
